version: '3.5'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  aspnet:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      ASPNETCORE_URLS: http://aspnet:5000/
